# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
