# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_faculty_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchLeft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('icon', models.CharField(max_length=50, null=True)),
                ('content', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('icon', models.CharField(max_length=50, null=True)),
                ('content', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
