# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_faculty_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rank',
        ),
    ]
