# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20160220_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
