# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='image',
            field=models.ImageField(null=True, upload_to='intro'),
        ),
    ]
