# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20160220_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
