# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_faculty_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
