# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 12:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20160127_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchintro',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 27, 12, 29, 54, 989953, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='researchintro',
            name='made',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
