# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_faculty_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('rank', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('made', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomesticJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('rank', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('made', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('rank', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('made', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
