# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_news_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default=b'media/student/eel.jpg', null=True, upload_to=b'students/'),
        ),
    ]
