# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
