# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20160229_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=b'media/student/eel.jpg', null=True, upload_to=b'students/'),
        ),
    ]
