# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_photographcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
