# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_calender'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
