# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20160130_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calender',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
