# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20160130_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('small_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('code', models.CharField(max_length=255, null=True)),
                ('credit', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
