# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_lecture_usefullink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResearchLeft',
            new_name='Research',
        ),
        migrations.DeleteModel(
            name='ResearchRight',
        ),
        migrations.AlterField(
            model_name='photograph',
            name='category',
            field=models.CharField(choices=[('category1', 'Category1'), ('category4', 'NEWcategory'), ('category2', 'NEWER')], max_length=255, null=True),
        ),
    ]
