# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20160130_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
