# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='gmap_lat',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='gmap_lng',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='gmap_title',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='published',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='title',
        ),
        migrations.AddField(
            model_name='publication',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
