# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20160207_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[(b'international', b'International Journals'), (b'domestic', b'Domestic Journals'), (b'book', b'Books')], default='international', max_length=255),
            preserve_default=False,
        ),
    ]
