# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_publication_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
