# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_collaborator_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('degree', models.CharField(max_length=255, null=True)),
                ('graduated', models.CharField(max_length=255, null=True)),
                ('works', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
