# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_alumnus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnus',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='alumnus',
            name='graduated',
        ),
        migrations.RemoveField(
            model_name='alumnus',
            name='works',
        ),
        migrations.AddField(
            model_name='alumnus',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
