# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20160208_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
