# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20160208_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
