# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20160208_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
