# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_lecture_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='text',
        ),
    ]
