# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_remove_contact_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='email_webmaster',
        ),
        migrations.AddField(
            model_name='contact',
            name='email_professor',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
