# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20160208_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
